# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions
   
    conda install numpy
    pip install numpy

In [ ]:
pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3,4,5]
type(my_list)

In [ ]:
arr = np.array(my_list)
type(arr)

In [ ]:
arr

In [ ]:
my_mat_list = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat_list)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,11)

In [ ]:
rng=range(0,11,2)
np.array(rng)

In [ ]:
np.arange(0,11,2)

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros((3,5))

In [ ]:
np.zeros((5,5))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(5,5)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

In [ ]:
np.random.randint(1,100,5)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(30)


In [ ]:
arr

In [ ]:
ranarr

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(1,25)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr = np.random.randint(0,50,10)
# arr = np.arange(25)
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr = np.arange(25)
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
rarr= arr.reshape(25,1)

In [ ]:
rarr.shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

# NumPy Indexing and Selection

Now lets discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
#Show
arr

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

In [ ]:
#Get values in a range
arr[1:5]

In [ ]:
#Get values in a range
arr[0:5]

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
arr[1:5]=100
arr

In [ ]:
lst=[0,1,2,3,4,5,6,7,8,9,10]

In [ ]:
lst[2]=100
lst

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

In [ ]:
#Important notes on Slices
slice_of_arr = arr[1:5]

#Show slice
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

In [ ]:
arr_copy[0:5] = 55

In [ ]:
arr_copy

In [ ]:
arr

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [3]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#Indexing row
arr_2d[2:]


array([[35, 40, 45]])

In [17]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [7]:
# Getting individual element value
arr_2d[1,1]

25

In [11]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2,:]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr>4

In [21]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr[arr < 4]

array([1, 2, 3])

In [25]:
x = 4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [30]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [36]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [37]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
np.max(arr) #same as arr.max()

9

In [40]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [41]:
np.log(arr)

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [44]:
list(arr).count(arr.max())

1

# Great Job!